## Numpy Exercise
This exercise deals with numpy arrays. These objects are the fundamental building blocks of any scientific library in Python.

**Remark**: Add a new cell above the expected output. Otherwise you would overwrite the expected result!

#### Import Numpy

In [2]:
import numpy as np

### 1. Create Numpy Arrays
**Create an array of 12 zeros.**

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

**Create a $3 \times 4$ - Matrix containing only zeros.**

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**Create an array of 10 fives.**

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

**Create an array of the integers from 1 to 12 and reshape the array to get a $3 \times 4$-Matrix.**  
The matrix should be called **mat**.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### 2. Indexing and Selection

**From the previously defined matrix extract the value 6.**

6

**Create an array from integers 1 to 32 and reshape it to an $4 \times 8$ matrix. The matrix should be called mat.**

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32]])

**Select the first two columns.**

array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26]])

**Select every second column, starting with column 0.**

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31]])

**Extract every value of the matrix which is larger than 13.**

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
       31, 32])

**Extract all even values of the matrix.**

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

**Extract all elements which are larger than 13 and smaller than 24.**

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

### 3. Basic operations with numpy

**Compute the sum of all elements in the matrix.**

528

**Compute the column-wise sum.**

array([ 36, 100, 164, 228])

**Compute the row-wise sum.**

array([52, 56, 60, 64, 68, 72, 76, 80])

**Compute the mean and the standard deviation of the columns.**

array([  4.5,  12.5,  20.5,  28.5])

array([ 2.29128785,  2.29128785,  2.29128785,  2.29128785])

**Compute the inner product of the matrix with its transpose.**

array([[ 204,  492,  780, 1068],
       [ 492, 1292, 2092, 2892],
       [ 780, 2092, 3404, 4716],
       [1068, 2892, 4716, 6540]])